m-builtins-bad.mzn:16:
  symbol error: `foldl' undeclared
m-builtins-bad.mzn:17:
  symbol error: `foldr' undeclared
m-builtins-bad.mzn:20:
  symbol error: `holds' undeclared
m-builtins-bad.mzn:25:
  symbol error: `int_eq' undeclared
m-builtins-bad.mzn:26:
  symbol error: `float_plus' undeclared
m-builtins-bad.mzn:27:
  symbol error: `float_lin_eq_reif' undeclared
% -- pretty-print after type-inst-checking --------------
int: x = 1;

int: y = 2;

int: z = 3;

bool: b = true;

int: i1 = foldl(x, y, z);

int: i2 = foldr(x, y, z);

int: i4 = holds(x);

int: i5 = int_eq(x, y);

int: i6 = float_plus(x, y, z);

int: i7 = float_lin_eq_reif(x, y, z, b);

solve satisfy;
