[1, 8, 1, 2, 1, 3, 8, 5, 19, 1, 13, 5, 14, 18, 1, 16, 5, 19, 8, 1, 12, 12, 2, 15, 12, 1, 3, 8, 9, 14, 3, 8, 9, 12, 12, 1, 19, 14, 1, 16, 19, 14, 1, 9, 12, 5, 4, 2, 5, 3, 15, 13, 5, 20, 9, 14, 19, 25, 19, 20, 5, 13, 15, 3, 3, 1, 13, 19, 5, 1, 1, 19, 1, 13, 1, 3, 8, 5, 1, 12, 1, 19, 11, 1, 19, 14, 1, 7, 20, 9, 14, 24, 5, 14, 1, 11, 9, 19, 9, 14, 1, 1, 12, 20, 1, 20, 9, 13, 5, 12, 25, 1, 14, 9, 12, 5, 9, 12, 1, 14, 5, 4, 16, 5, 3, 1, 14, 7, 21, 12, 1, 7, 19, 1, 8, 1, 2, 1, 18, 13, 1, 14, 1, 2, 15, 18, 20, 5, 4, 1, 4, 1, 14, 7, 21, 10, 18, 1, 14, 23, 1, 12, 1, 12, 5, 4, 1, 19, 20, 1, 20, 19, 9, 3, 15, 14, 11, 14, 5, 5, 20, 5, 14, 19, 5, 7, 15, 25, 1]
a h a b a c h e s a m e n r a p e s h a l l b o l a c h i n c h i l l a s n a p s n a i l e d b e c o m e t i n s y s t e m o c c a m s e a a s a m a c h e a l a s k a s n a g t i n x e n a k i s i n a a l t a t i m e l y a n i l e i l a n e d p e c a n g u l a g s a h a b a r m a n a b o r t e d a d a n g u j r a n w a l a l e d a s t a t s i c o n k n e e t e n s e g o y a 

ahab*aches*amen
rape*shall*bola
chinchilla*snap
snailed**become
***tin*system**
occam*sea*asama
che*alaska*snag
tin*xenakis*ina
alta*timely*ani
leila*ned*pecan
**gulags*aha***
barman**aborted
adan*gujranwala
leda*stats*icon
knee*tense*goya

----------
%%  runtime:       0.494 (494.904000 ms)
%%  solvetime:     0.067 (67.047000 ms)
%%  solutions:     1
%%  variables:     189
%%  propagators:   78
%%  propagations:  2936
%%  nodes:         135
%%  failures:      38
%%  peak depth:    66
%%  peak memory:   1804 KB
