var bool: BOOL____00001 :: is_defined_var :: var_is_introduced;
var bool: BOOL____00002 :: is_defined_var :: var_is_introduced;
var bool: x1;
var bool: x2;
var bool: x3;
constraint array_bool_and([BOOL____00001, x2], BOOL____00002) :: defines_var(BOOL____00002);
constraint array_bool_or([BOOL____00002, x3], true);
constraint bool_eq_reif(x1, false, BOOL____00001) :: defines_var(BOOL____00001);
solve satisfy;
