var bool: BOOL____00001 :: is_defined_var :: var_is_introduced;
var bool: BOOL____00002 :: is_defined_var :: var_is_introduced;
var bool: BOOL____00003 :: is_defined_var :: var_is_introduced;
var 1..3: x;
array [1..3] of var bool: ys = [BOOL____00001, BOOL____00002, BOOL____00003];
constraint int_eq_reif(x, 1, BOOL____00001) :: defines_var(BOOL____00001);
constraint int_eq_reif(x, 2, BOOL____00002) :: defines_var(BOOL____00002);
constraint int_eq_reif(x, 3, BOOL____00003) :: defines_var(BOOL____00003);
solve satisfy;
